### ISSUE TITLE
[Feature request] Code snippets storage

### ISSUE THREAD

**Issue by ThijsZijdel** [fosslife/devtools-x#107]
## Context:
As a developer, I often find myself reusing code snippets/ commands across various projects and environments. Having an efficient and organized way to store and retrieve these snippets within devtools-x would greatly enhance productivity and ensure consistency.

<img width="981" alt="Screenshot 2024-08-28 at 22 14 49" src="https://github.com/user-attachments/assets/59d79072-8252-46c1-aaa6-f79d6f8a6acb">

* Idea/Reference App: [SnippetsLab](https://apps.apple.com/us/app/snippetslab/id1006087419?mt=12)

## Proposed scope:

- [x] **Snippet Creation**: Ability to create and save code snippets within the app. This includes support for multiple languages, syntax highlighting, and formatting options. (Our monaco editor)

- [ ] **Organization**: Allow users to organize snippets into folders, tags, or categories for easy navigation. Option to add descriptive titles and notes to each snippet.

- [ ] **Search & Filter**: Implement a powerful search functionality that enables users to quickly find snippets based on keywords, tags, or language. _Will combine this with a more advanced keywords based search hook for all the modules aswell_

- [ ] ❓ **Snippet Sharing** : Option to share snippets with team members or export them in various formats (e.g., JSON, plain text).

Questions: @Sparkenstein  What is your preferred way of storing files/snippets? Also, are there any additional features you'd like to see in the snippet storage system?

**Edit:** Perhaps wrap the db file storage used on the "JSON Tools" module?  `await db.get<any>("snippets/group/file");`

_Additional note/ idea: Would love to make this system reusable for eg. AI prompts, currently using a combination of notes, snippetsLab en notion._

**Comment by Sparkenstein** [comment]
This was in TODO from a long time, glad that you picked it up.

For storage, Ideally we should use something like SQLite, it's doable with rust, If you want I can set up a basic SQLite storage to build on top of. Finding/searching with SQLite will be cheaper than storing text in json. If you want to take a stab at it, that's fine by me. 

(I don't mind existing `tauri-plugin-store`, but it was meant for storing small data like settings or config, and it doesn't provide any way to group/search/find etc, if store grows it will be costly, plus storing string inside JSON will need managing escape sequences etc. It's better to avoid it instead)

**Comment by ThijsZijdel** [comment]
@Sparkenstein could u take a look at [the db setup](https://github.com/ThijsZijdel/devtools-x/tree/feat/sqlite) within [main.rs](https://github.com/ThijsZijdel/devtools-x/blob/feat/sqlite/src-tauri/src/main.rs) having trouble getting the migrations to spin up 🤷🏼

**Comment by Sparkenstein** [comment]
Sorry for the delay, weekdays are busy always. will take a look around Friday.

**Comment by Sparkenstein** [comment]
Sorry for the delay x2, migrations are running fine I checked by adding one more up migration, it creates db and modifies it correctly. 
the database.ts file is wrong, can you point out any specific issue you are facing?

**Comment by Sparkenstein** [comment]
![image](https://github.com/user-attachments/assets/e4496fba-7166-493a-901a-e8bc2de17031)

in terms of setup everything looks good to me otherwise

**Comment by Sparkenstein** [comment]
Are you taking this one up? Otherwise I have some free time this week I can take a look

**Comment by ThijsZijdel** [comment]
Yes thanks, currently working on this

**Comment by ThijsZijdel** [comment]
Found the issue I had, snippet storage is working perfectly. 
Will be pushing the snippet manager probably later tonight 🎉
