### ISSUE TITLE
Devtools 1.7.0 on Linux (Debian 11) shows a blank window

### ISSUE THREAD

**Issue by GlacierFox** [fosslife/devtools-x#23]
Installed using the Deb on Debian 11. App just loads up to a white screen with nothing to press or interact with.

**Comment by shirish87** [comment]
Same issue with the AppImage build on Linux Mint 21 Cinnamon. Opening devtools in devtools-x points to a CSP issue:

```
Refused to load tauri://localhost/assets/react-markdown.356c3eb0.js because it does not appear in the script-src directive of the Content Security Policy.
```


The `deb` installation fails to run with the following error:
```
dev-tools: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

![image](https://user-images.githubusercontent.com/304687/191065236-ea43e3e6-fbe0-4168-a8e8-7448a58ddbf3.png)

**Comment by Sparkenstein** [comment]
Apologies for delayed reply. yes this was an issue with CSP, which I have removed completely (the image compressor module)
I have also tested the application on Mac, windows and Linux (wsl) now. please try latest release v1.7.1 and let me know if the issue still persists.

The image module will be rewritten and will be reintroduced in upcoming versions

**Comment by shirish87** [comment]
Can confirm v1.7.1 AppImage works perfectly fine on Linux Mint 21 Cinnamon. :+1:
