### ISSUE TITLE
Bug - crash because of db util on macos

### ISSUE THREAD

**Issue by Sparkenstein** [fosslife/devtools-x#28]
As pointed out by @jackphilippi  in   https://github.com/fosslife/devtools-x/issues/22#issuecomment-1253282386

The tool fails with some db error. need more information

**Comment by Sparkenstein** [comment]
TBH I am not being able to reproduce this, even on a system setup from scratch.
will keep this open just incase someone else also faces the same issue

**Comment by jackphilippi** [comment]
Thanks @Sparkenstein. I'll continue digging in the new week and see if I can get any further with this. I have an older (non-M1) mac that I can test it on too, so I'll report back soon.

**Comment by Sparkenstein** [comment]
rewrote the entire db logic, this should 100% be fixed now
