### ISSUE TITLE
[Feature Request] regexp tool

### ISSUE THREAD

**Issue by farfromrefug** [fosslife/devtools-x#32]
I know you already have a regexp tool. Would be awesome for it to be improved.
The online one i currently use is https://regexr.com/ which is open source https://github.com/gskinner/regexr/ (but in php)

**Comment by Sparkenstein** [comment]
took 2 years (precisely  2 years accidentally), but finally I got the time to rewrote the damned regex tester. tested multiple string with regexr we have the same output. release tomorrow with tauri  v2.

![image](https://github.com/user-attachments/assets/d9d3c5bd-95ba-4fd8-9df6-ee8a076485e5)

**Comment by farfromrefug** [comment]
@Sparkenstein that is awesome. Might add that a very nice feature of regexr is the hover tool on result text. It allows to see matched groups which is crazy useful.
Thanks again for the great work!

**Comment by Sparkenstein** [comment]
I think that's a great idea. let me see if I can add that. sound easy enough we already have matched groups
