### ISSUE TITLE
[Feature Request] improve color tools 

### ISSUE THREAD

**Issue by farfromrefug** [fosslife/devtools-x#36]
Would be awesome to have a lot more things in the color tool like https://www.colorhexa.com/e5d461, especially the color schemes tools

**Comment by ThijsZijdel** [comment]
@farfromrefug Working on this atm. Pull request is ready with most of the features #84 

The harmonies will be coming in the next pull request 👍 

![Harmonies](https://github.com/user-attachments/assets/5025e270-9c6e-4833-90d3-d3da7b07f056)

**Comment by ThijsZijdel** [comment]
@Sparkenstein can be closed for now imo

**Comment by Sparkenstein** [comment]
This is done, lots of new features are added in color space. closing this as resolved! 
thanks to @ThijsZijdel for all the work 💪
