### ISSUE TITLE
Feat request - cron explain / builder

### ISSUE THREAD

**Issue by khuongduybui** [fosslife/devtools-x#52]
Something like https://crontab.guru/

**Comment by Sparkenstein** [comment]
Yes this is something in milestone, will release once I have reduced scope to something I can implement over the weekend.

**Comment by Sparkenstein** [comment]
I have added a simple version of crontab parsing.  didn't concentrate much on the design but it gets the job done



![image](https://github.com/fosslife/devtools-x/assets/24642451/6ab05164-d9ad-4ae3-9366-bf22e9b21460)
