### ISSUE TITLE
Unknown error while interacting with the clipboard

### ISSUE THREAD

**Issue by ekasprzak** [fosslife/devtools-x#56]
Hi, starting with version 2.5.0 I can't run devtools anymore:

```
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.3/src/lib.rs:2021:55:
called `Result::unwrap()` on an `Err` value: Unknown { .. } - "Unknown error while interacting with the clipboard: X11 server connection timed out because it was unreachable"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

Same with recently released v 2.6.0

**All is fine with 2.4.0**
Fedora 39 / GNOME / Xorg

**Comment by Sparkenstein** [comment]
apologies, I will try to reproduce this on fedora tomorrow. 
can you tell me at what page you got the error? which clipboard?

**Comment by Sparkenstein** [comment]
I was able to reproduce copy button not working, but didn't face crash at least, looks like some dependency is missing in fedora, I will check

**Comment by ekasprzak** [comment]
Hi, this error appeared during the start of devtools, so I couldnt even open the app itself.
I just tried with most recent 2.7.0 - it runs and I cant see any errors now.
Thanks, I will close the issue then.
