### ISSUE TITLE
supports aarch64-apple-darwin: targets Apple silicon 

### ISSUE THREAD

**Issue by reslear** [fosslife/devtools-x#57]

**Comment by Sparkenstein** [comment]
Github CI doesn't support arm macs yet in my knowledge. I am waiting for those myself, but x86 darwin package works on mac just fine, without any performance issue. 
I will still release arm versions as soon as github CI starts supporting arm macs.

**Comment by nileshmali** [comment]
@Sparkenstein Apple Silicone runners now available on Github.
Please check https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners

**Comment by Sparkenstein** [comment]
Ah great, so `macos-latest` is the label for arm version, I am already using that. does that mean existing packages are already built for arm?

**Comment by nileshmali** [comment]
I think arch needs to be set, I can give it a stab. Will share the pr over the weekend.

**Comment by Sparkenstein** [comment]
Aarch64 images are now available to download from release tab

**Comment by reslear** [comment]
![CleanShot 2024-06-19 at 17 25 17@2x](https://github.com/fosslife/devtools-x/assets/12596485/8771e183-ea8f-43eb-8cea-cc7d3e2f001f)

**Comment by Sparkenstein** [comment]
Weird, worked normally on my m2 mac. maybe your download was actually corrupt or something?

**Comment by Puujee0238** [comment]
+1 
<img width="269" alt="image" src="https://github.com/fosslife/devtools-x/assets/14870960/8c40cff1-d1be-4934-b34d-4b339ba00a2f">

**Comment by Sparkenstein** [comment]
Most likely this is because there are no version change in the release. will implement some new feature and do a version upgrade and release one more time this weekend. that should technically resolve the issue. 

i am using the same release.yml for my another project fosslife/truthy. it works there so far I am assuming it should work here too

**Comment by Sparkenstein** [comment]
Apologies, it's the OSX shenanigans, I have only work macbook, I can't generate certificate from that. will try to get a resale macbook soon. 

For now 

```sh
xattr -r -c /Applications/dev-tools.app
```
Is the solution as mentioned by @reslear. 
will mention this in README too.
