### ISSUE TITLE
[Feature request] - Visualize Color Wheels

### ISSUE THREAD

**Issue by ThijsZijdel** [fosslife/devtools-x#96]
Color harmonies/ visualisation like [Atmos style](https://app.atmos.style/)

<img width="1094" alt="Screenshot 2024-08-10 at 15 01 12" src="https://github.com/user-attachments/assets/77b03cc5-1839-4bcb-ab89-7b5548448909">

## Current progress: 
Generation and calculations are mostly done, currently working on a new improved picker;

![Screenshot 2024-08-10 at 15 00 56](https://github.com/user-attachments/assets/1b1775e2-5886-4f9b-90d3-056ab46f86c5)

PR will come in the upcoming week, stay tuned.

**Comment by Sparkenstein** [comment]
I tried it it's actually good if we can make  it work

**Comment by ThijsZijdel** [comment]
Had some busy days, but the visualisation is for 90% done. Only needs some code & ui cleanup.

Picking of a color within one of the custom color wheel-pickers is kind of sketchy atm, prob this sunday/ next week.

![Screenshot 2024-08-14 at 23 01 45](https://github.com/user-attachments/assets/88bd1490-e960-45df-9242-37180b5ab094)

![Screenshot 2024-08-14 at 23 01 53](https://github.com/user-attachments/assets/8f6e5d4a-11ea-4588-9ad0-51ee0906f5c2)

**Comment by ThijsZijdel** [comment]
https://github.com/user-attachments/assets/2a048c04-a7ab-40a1-84be-54d809bb92c7

Used: [this online video compressor](https://www.youcompress.com/mov/) 👀

**Comment by ThijsZijdel** [comment]
Closing this since PR is finished for now #103
