### ISSUE TITLE
bug: no scrolling is textarea text too large 

### ISSUE THREAD

**Issue by reslear** [fosslife/devtools-x#97]
![CleanShot 2024-08-12 at 18 14 52@2x](https://github.com/user-attachments/assets/687394fd-177d-44f7-bade-ab80685afd07)

**Comment by Sparkenstein** [comment]
Thanks for the report, 

![image](https://github.com/user-attachments/assets/32260774-1474-48e7-9bab-f6c3a74a2fb0)

Fix is available in 1.14.1
